# Generated by Django 5.0 on 2026-05-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('alquiler', 'Contrato de Alquiler'), ('nda', 'Acuerdo de Confidencialidad')], max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('firmantes', models.JSONField(default=list)),
                ('fecha_contrato', models.CharField(blank=True, max_length=100)),
                ('duracion', models.CharField(blank=True, max_length=200)),
                ('importe', models.CharField(blank=True, max_length=200)),
                ('banderas_rojas', models.JSONField(default=list)),
                ('riesgo_total', models.CharField(blank=True, choices=[('CRITICO', 'Crítico'), ('MEDIO', 'Medio'), ('BAJO', 'Bajo')], max_length=20)),
                ('resumen', models.TextField(blank=True)),
            ],
        ),
    ]
